"""starter.py - employers a fresh install can read on day one.

Twelve of the fifteen collectors are per-employer: they sit idle until
somebody names companies, and nobody can invent forty employer names cold.
That is the real onboarding barrier - not the config, not the resume, not
the search terms. Three sources need no list at all - USAJOBS, Remote OK
and NoDesk - and between them they are still a thin slice of the market.

WHAT IS IN HERE, AND WHAT IS DELIBERATELY NOT
Nationally-operating employers only. No regional names: a shipped pack
carrying one metro's employers is dead weight to everyone outside it and
reads as an oversight to everyone in it (decided 2026-08-04).

Chosen for BREADTH OF FUNCTION, not industry. Internal roles - IT, HR,
maintenance, accounting, facilities, security - exist at every employer, so
a wide employer base matters more than an industry-curated list. The sector
tag on each entry is there so somebody can delete what they do not want,
not so the list can be filtered into a specialism.

A FLAT LIST, added whole, rather than opt-in bundles. Bundles would put the
industry-curation mistake back in by the front door: a warehouse manager
who picks "logistics" never sees that the hospital down the road needs a
facilities supervisor.

EVERY ENTRY WAS MEASURED, NOT ASSUMED. Each name here was resolved to a
board and then collected from, and only names that returned live postings
survived. A name that cannot be read is worse than no name, because it teaches
somebody on their first afternoon that the tool does not work.

THE REFERENCES REPAIR THEMSELVES. Employers change ATS without announcing
it, and a stored reference that stops returning postings would otherwise leave
that employer silent for ever - indistinguishable, on screen, from one that is
simply not hiring. `collect` counts the consecutive collections on which a
board returns nothing, and after three it re-probes that ONE employer and
writes the new reference. See rediscover.heal_one for why that is not the
scheduled crawl this app refuses to be, and why a probe that finds nothing is
never allowed to blank a board.

So the pack is still a starting point somebody edits - the sector tags exist
to be deleted from - but it is no longer a list that quietly stops working.
"""
from __future__ import annotations

# The employer table below is GENERATED from a measurement run, and holds
# real career-site URLs, some of which are longer than the line limit on
# their own. Wrapping a URL to satisfy a linter makes it harder to read and
# impossible to copy, so the limit is lifted for this file only.
# ruff: noqa: E501
from typing import TYPE_CHECKING, Any, NamedTuple

from . import db

if TYPE_CHECKING:
    import sqlite3


class Employer(NamedTuple):
    name: str
    ats: str
    ats_ref: str
    sector: str
    careers_url: str
    # Postings the board returned when the pack was last measured. Kept so a
    # later re-measure can show what changed rather than only what broke.
    postings: int


# Regenerated by a measurement run against the live boards. MEASURED_ON is
# the date every COUNT below was taken, and the counts are the part that ages:
# nothing re-measures how many postings a board had, and nothing should, since
# walking fifty boards to update a number is the sweep rather than the repair.
#
# THE REFERENCES ARE A DIFFERENT MATTER and do not age in the same way - see
# the module docstring. An employer that moves is re-probed by `collect` after
# three empty collections, so `ats` and `ats_ref` correct themselves while
# `postings` stays a historical record of one day.
MEASURED_ON = "2026-08-06"

EMPLOYERS: tuple[Employer, ...] = (
    # facilities and services
    Employer("ABM Industries", "oracle_hcm", "eiqg.fa.us2.oraclecloud.com|CX_1001", "facilities and services",
             "https://www.abm.com/", 50),
    # finance and insurance
    Employer("American Express", "oracle_hcm", "egug.fa.us2.oraclecloud.com", "finance and insurance",
             "https://careers.americanexpress.com/en/sites/CX_1", 50),
    Employer("Bank of America", "workday", "ghr|wd1|lateral-us", "finance and insurance",
             "https://careers.bankofamerica.com/en-us", 20),
    Employer("Citi", "workday", "citi|wd5|2", "finance and insurance",
             "https://jobs.citi.com", 20),
    Employer("Nationwide", "workday", "nationwide|wd1|Nationwide_Career", "finance and insurance",
             "https://careers.nationwide.com", 20),
    Employer("Travelers", "workday", "travelers|wd5|External", "finance and insurance",
             "https://careers.travelers.com", 20),
    Employer("U.S. Bank", "workday", "usbank|wd1|US_Bank_Careers", "finance and insurance",
             "https://careers.usbank.com/global/en", 19),
    # health
    Employer("CVS Health", "workday", "cvshealth|wd1|CVS_Health_Careers", "health",
             "https://jobs.cvshealth.com/us/en/ftw-jobs", 20),
    Employer("Centene", "workday", "centene|wd5|centene_external", "health",
             "https://jobs.centene.com/us/en/", 20),
    Employer("Cigna", "workday", "cigna|wd5|cignacareers", "health",
             "https://jobs.thecignagroup.com/us/en", 20),
    Employer("Elevance Health", "workday", "elevancehealth|wd1|ANT", "health",
             "https://careers.elevancehealth.com", 20),
    Employer("Fresenius Medical Care", "workday", "freseniusmedicalcare|wd3|fme", "health",
             "https://jobs.freseniusmedicalcare.com", 20),
    Employer("Humana", "workday", "humana|wd5|CenterWell_External_Career_Site", "health",
             "https://careers.humana.com/us/en/search-results", 20),
    Employer("Molina Healthcare", "oracle_hcm", "hckd.fa.us2.oraclecloud.com|CX_1", "health",
             "https://careers.molinahealthcare.com", 50),
    Employer("Quest Diagnostics", "oracle_hcm", "hdox.fa.us6.oraclecloud.com|CX_1", "health",
             "https://careers.questdiagnostics.com", 50),
    # hospitality and food
    Employer("Hilton", "oracle_hcm", "efet.fa.us2.oraclecloud.com|CX_1", "hospitality and food",
             "https://jobs.hilton.com", 50),
    Employer("Marriott International", "oracle_hcm", "ejwl.fa.us2.oraclecloud.com|CX", "hospitality and food",
             "https://careers.marriott.com/", 50),
    Employer("Sodexo", "smartrecruiters", "Sodexo", "hospitality and food",
             "https://www.sodexo.com/working-at-sodexo/find-a-job", 100),
    # logistics
    Employer("C.H. Robinson", "workday", "chrobinson|wd5|CHRobinson", "logistics",
             "https://www.chrobinson.com/en-us/about-us/careers/", 20),
    Employer("J.B. Hunt Transport Services", "workday", "jbhunt|wd501|Careers", "logistics",
             "https://careers.jbhunt.com", 20),
    Employer("Old Dominion Freight Line", "workday", "odfl|wd1|ODFL_Careers", "logistics",
             "https://olddominionfreightline.com/us/en/careers.html", 20),
    Employer("Penske Truck Leasing", "oracle_hcm", "fa-euyk-saasfaprod1.fa.ocs.oraclecloud.com|PenskeCareers", "logistics",
             "https://penske.jobs/", 50),
    # manufacturing
    Employer("Boeing", "workday", "boeing|wd1|EXTERNAL_CAREERS", "manufacturing",
             "https://jobs.boeing.com", 20),
    Employer("Caterpillar", "workday", "cat|wd5|CaterpillarCareers", "manufacturing",
             "https://www.caterpillar.com", 20),
    Employer("Cummins", "oracle_hcm", "fa-espx-saasfaprod1.fa.ocs.oraclecloud.com|CX_1", "manufacturing",
             "https://cummins.jobs/", 50),
    Employer("Emerson Electric", "oracle_hcm", "hdjq.fa.us2.oraclecloud.com|CX_1", "manufacturing",
             "https://www.emerson.com/en/corporate", 50),
    Employer("GE Aerospace", "workday", "geaerospace|wd5|GE_ExternalSite", "manufacturing",
             "https://careers.geaerospace.com/global/en/investing-in-manufacturing", 20),
    Employer("Honeywell", "oracle_hcm", "ibqbjb.fa.ocs.oraclecloud.com", "manufacturing",
             "https://careers.honeywell.com/en/sites/Honeywell", 50),
    Employer("Stanley Black and Decker", "workday", "sbdinc|wd1|Stanley_Black_Decker_Career_Site", "manufacturing",
             "https://www.stanleyblackanddecker.com", 20),
    # retail
    Employer("Albertsons", "oracle_hcm", "eofd.fa.us6.oraclecloud.com|CX_1001", "retail",
             "https://www.albertsons.com/", 50),
    Employer("AutoZone", "oracle_hcm", "egud.fa.us2.oraclecloud.com", "retail",
             "https://careers.autozone.com/hcmUI/CandidateExperience/en/sites/CX_1", 50),
    Employer("Kroger", "oracle_hcm", "eluq.fa.us2.oraclecloud.com", "retail",
             "https://www.krogerfamilycareers.com/en/sites/CX_2001", 50),
    Employer("Macy's", "oracle_hcm", "ebwh.fa.us2.oraclecloud.com|CX_1001", "retail",
             "https://www.macys.com/", 50),
    Employer("Nordstrom", "workday", "nordstrom|wd501|nordstrom_careers", "retail",
             "https://careers.nordstrom.com", 20),
    Employer("Petco", "workday", "petco|wd504|External", "retail",
             "https://careers.petco.com", 20),
    Employer("Sherwin-Williams", "oracle_hcm", "ejhp.fa.us6.oraclecloud.com|CX_2", "retail",
             "https://careers.sherwin-williams.com/us/en/home.html", 50),
    Employer("Target", "workday", "target|wd5|targetcareers", "retail",
             "https://corporate.target.com/careers", 20),
    # telecom and technology
    Employer("AT&T", "workday", "att|wd1|ATTGeneral", "telecom and technology",
             "https://www.att.jobs/", 20),
    Employer("Accenture", "workday", "accenture|wd103|AccentureCareers", "telecom and technology",
             "https://www.accenture.com/us-en/careers", 19),
    Employer("Adobe", "workday", "adobe|wd5|external_experienced", "telecom and technology",
             "https://careers.adobe.com/us/en/c/engineering-and-product-jobs", 20),
    Employer("Comcast", "workday", "comcast|wd5|Comcast_Careers", "telecom and technology",
             "https://jobs.comcast.com", 20),
    Employer("DXC Technology", "workday", "dxctechnology|wd1|DXCJobs", "telecom and technology",
             "https://careers.dxc.com", 20),
    Employer("Kyndryl", "workday", "kyndryl|wd5|KyndrylEarlyCareers", "telecom and technology",
             "https://www.kyndryl.com/us/en/careers", 20),
    Employer("Oracle", "oracle_hcm", "eeho.fa.us2.oraclecloud.com", "telecom and technology",
             "https://careers.oracle.com/en/sites/jobsearch", 50),
    Employer("T-Mobile", "workday", "tmobile|wd1|External", "telecom and technology",
             "https://careers.t-mobile.com/", 20),
    Employer("Verizon", "workday", "verizon|wd12|verizon-careers", "telecom and technology",
             "https://mycareer.verizon.com/", 20),
    Employer("Workday", "workday", "workday|wd5|Workday", "telecom and technology",
             "https://www.workday.com", 20),
    # utilities and energy
    Employer("Baker Hughes", "workday", "bakerhughes|wd5|BakerHughes", "utilities and energy",
             "https://www.bakerhughes.com", 20),
    Employer("Duke Energy", "workday", "dukeenergy|wd1|search", "utilities and energy",
             "https://www.duke-energy.com/our-company/careers", 20),
    Employer("Xcel Energy", "workday", "xcelenergy|wd1|External", "utilities and energy",
             "https://jobs.xcelenergy.com", 20),
)


def by_sector() -> dict[str, list[Employer]]:
    """The pack grouped for display. Insertion order per sector is the order
    they are listed above, which is alphabetical within each group.
    """
    out: dict[str, list[Employer]] = {}
    for employer in EMPLOYERS:
        out.setdefault(employer.sector, []).append(employer)
    return out


def seed(con: sqlite3.Connection) -> tuple[int, int]:
    """Adds the pack to this profile. Returns (added, already_there).

    Never overwrites an employer the person already has, even when the pack
    knows a different board for it: their entry may be a correction, and a
    seed that quietly reverts a correction is worse than one that skips.
    """
    added = skipped = 0
    for employer in EMPLOYERS:
        if db.get_company(con, employer.name) is not None:
            skipped += 1
            continue
        db.upsert_company(con, employer.name, careers_url=employer.careers_url,
                          ats=employer.ats, ats_ref=employer.ats_ref,
                          probe_status="yielding", origin=db.SEEDED)
        added += 1
    return added, skipped


def as_dicts() -> list[dict[str, Any]]:
    """For `--json` output and for anything that wants the pack without
    importing the NamedTuple.
    """
    return [e._asdict() for e in EMPLOYERS]
